-- =====================================================================
-- TallyBust — Supabase schema
-- Run this once in your project's SQL Editor (Supabase Dashboard →
-- SQL Editor → New query → paste all of this → Run).
--
-- Model: single business per authenticated Owner account, identified by
-- the auth.uid() that created it (stored as user_id on every table).
-- Staff members each get their own separate, independent Supabase Auth
-- account too (see is_staff_of() and src/staffAuth.js), but every row
-- they read or write is still scoped to their employer's user_id — they
-- never get an account of their own business. Row Level Security below
-- enforces that boundary on every table.
-- =====================================================================

create extension if not exists "uuid-ossp";

-- ---------------------------------------------------------------------
-- settings: one row per user — business name, currency
-- ---------------------------------------------------------------------
create table if not exists public.settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  business_name text not null default 'My Business',
  currency text not null default '₦',
  owner_email text,
  trial_start_date date not null default current_date,
  subscription_status text not null default 'trial' check (subscription_status in ('trial', 'active', 'expired')),
  subscription_expires_at date,
  is_admin boolean not null default false,
  -- Short, shareable code (e.g. "K3F9QX") the Owner gives to staff — it's
  -- baked into each staff member's own login so their account only ever
  -- exists for this one business. Auto-generated by a trigger below.
  business_code text unique,
  updated_at timestamptz not null default now()
);

alter table public.settings enable row level security;

create policy "settings: owner read" on public.settings
  for select using (auth.uid() = user_id);
create policy "settings: owner insert" on public.settings
  for insert with check (auth.uid() = user_id);
create policy "settings: owner update" on public.settings
  for update using (auth.uid() = user_id);

create or replace function public.generate_business_code()
returns text
language sql
as $$
  select upper(substr(md5(gen_random_uuid()::text), 1, 6));
$$;

create or replace function public.set_business_code()
returns trigger
language plpgsql
as $$
begin
  if new.business_code is null then
    loop
      new.business_code := public.generate_business_code();
      exit when not exists (select 1 from public.settings where business_code = new.business_code);
    end loop;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_business_code on public.settings;
create trigger trg_set_business_code
  before insert on public.settings
  for each row execute function public.set_business_code();

-- is_admin() is used below and by the app's admin dashboard
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
as $$
  select coalesce((select is_admin from public.settings where user_id = auth.uid()), false);
$$;

create policy "settings: admin read all" on public.settings
  for select using (public.is_admin());
create policy "settings: admin update all" on public.settings
  for update using (public.is_admin());

-- is_staff_of() — true if the signed-in user is a staff member (their own,
-- independent Supabase Auth account, linked via staff.auth_user_id) of the
-- business owned by `business_owner`. Used throughout so a staff member's
-- own phone can sign in and work with their employer's data directly,
-- without ever sharing the Owner's login.
create or replace function public.is_staff_of(business_owner uuid)
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from public.staff
    where user_id = business_owner and auth_user_id = auth.uid()
  );
$$;

create policy "settings: staff read" on public.settings
  for select using (public.is_staff_of(user_id));

-- ---------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------
create table if not exists public.products (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text not null default 'Uncategorized',
  sku text not null,
  qty integer not null default 0,
  min_stock integer not null default 0,
  purchase_price numeric(12,2) not null default 0,
  selling_price numeric(12,2) not null default 0,
  supplier text,
  expiry date,
  batch text,
  -- Unit-sale fields: lets a pack-stocked item (e.g. a box of tablets)
  -- also be sold one loose unit at a time. See migration_v6_unit_sales.sql
  -- for the full explanation of how loose_units is kept in sync.
  unit_sale_enabled boolean not null default false,
  unit_name text,
  unit_qty_per_pack integer not null default 0,
  unit_price numeric(12,2) not null default 0,
  loose_units integer not null default 0,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (user_id, sku)
);

alter table public.products enable row level security;

create policy "products: owner read" on public.products
  for select using (auth.uid() = user_id);
create policy "products: owner insert" on public.products
  for insert with check (auth.uid() = user_id);
create policy "products: owner update" on public.products
  for update using (auth.uid() = user_id);
create policy "products: owner delete" on public.products
  for delete using (auth.uid() = user_id);
create policy "products: admin read all" on public.products
  for select using (public.is_admin());
create policy "products: staff read" on public.products
  for select using (public.is_staff_of(user_id));
create policy "products: staff insert" on public.products
  for insert with check (public.is_staff_of(user_id));
create policy "products: staff update" on public.products
  for update using (public.is_staff_of(user_id));

create index if not exists products_user_idx on public.products(user_id);

-- ---------------------------------------------------------------------
-- stock_history: every Stock In / Stock Out (sale) / Refund event.
-- 'count' is kept in the check constraint only so older rows recorded
-- before Stock Count was removed from the app remain valid — the app
-- itself no longer writes that type.
-- ---------------------------------------------------------------------
create table if not exists public.stock_history (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  product_name text not null,
  type text not null check (type in ('stock-in', 'sale', 'count', 'unit-sale', 'refund')),
  qty integer not null,
  unit_price numeric(12,2) not null default 0,
  staff text not null default 'Admin',
  occurred_on date not null default current_date,
  captured_photo text,
  created_at timestamptz not null default now()
);

alter table public.stock_history enable row level security;

create policy "history: owner read" on public.stock_history
  for select using (auth.uid() = user_id);
create policy "history: owner insert" on public.stock_history
  for insert with check (auth.uid() = user_id);
create policy "history: admin read all" on public.stock_history
  for select using (public.is_admin());
create policy "history: staff read" on public.stock_history
  for select using (public.is_staff_of(user_id));
create policy "history: staff insert" on public.stock_history
  for insert with check (public.is_staff_of(user_id));

create index if not exists stock_history_user_idx on public.stock_history(user_id);
create index if not exists stock_history_product_idx on public.stock_history(product_id);
create index if not exists stock_history_date_idx on public.stock_history(occurred_on);

-- ---------------------------------------------------------------------
-- app_config: single row holding the renewal message + payment
-- instructions the admin edits from the Admin Dashboard, visible to
-- every signed-in business (that's how an expired business sees it).
-- ---------------------------------------------------------------------
create table if not exists public.app_config (
  id int primary key default 1 check (id = 1),
  renewal_message text not null default 'Your TallyBust trial has ended. Renew your subscription to keep scanning and tracking stock.',
  payment_instructions text not null default 'Contact us to renew your subscription.',
  updated_at timestamptz not null default now()
);
insert into public.app_config (id) values (1) on conflict (id) do nothing;

alter table public.app_config enable row level security;

create policy "app_config: read all signed in" on public.app_config
  for select using (auth.role() = 'authenticated');
create policy "app_config: admin update" on public.app_config
  for update using (public.is_admin());
create policy "app_config: admin insert" on public.app_config
  for insert with check (public.is_admin());

-- ---------------------------------------------------------------------
-- Making yourself the admin: sign up once in the app with the account
-- you want to use as your admin login, then run this (with your own
-- email) to flip the flag that unlocks the Admin Dashboard for you:
--
--   update public.settings set is_admin = true
--     where user_id = (select id from auth.users where email = 'you@example.com');
-- ---------------------------------------------------------------------

-- ---------------------------------------------------------------------
-- staff: employees a business owner adds, each with a PIN and role.
-- Used for "Acting As" on the Staff page so scans/adjustments are
-- attributed to a real person, not a free-text label.
-- ---------------------------------------------------------------------
create table if not exists public.staff (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  pin text not null,
  role text not null default 'Cashier' check (role in ('Admin', 'Manager', 'Cashier', 'Storekeeper')),
  -- Links to this staff member's own, independent Supabase Auth account
  -- (built from Business Code + Username + PIN — see src/staffAuth.js) so
  -- they can sign in on their own phone. Null for staff added before this
  -- was introduced — use "Set up device login" on the Staff page for them.
  auth_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.staff enable row level security;

create policy "staff: owner all" on public.staff
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Lets a signed-in staff member read their OWN row right after logging
-- in (to learn their name/role/business) without seeing anyone else's.
create policy "staff: self read" on public.staff
  for select using (auth_user_id = auth.uid());

create index if not exists staff_user_idx on public.staff(user_id);
create index if not exists staff_auth_user_idx on public.staff(auth_user_id);

-- ---------------------------------------------------------------------
-- payment_receipts: a business attaches proof of payment here after
-- renewing; the admin reviews it on the Admin Dashboard and activates
-- the subscription once verified.
-- ---------------------------------------------------------------------
create table if not exists public.payment_receipts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  image text not null,
  note text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.payment_receipts enable row level security;

create policy "receipts: owner insert" on public.payment_receipts
  for insert with check (auth.uid() = user_id);
create policy "receipts: owner read own" on public.payment_receipts
  for select using (auth.uid() = user_id);
create policy "receipts: admin read all" on public.payment_receipts
  for select using (public.is_admin());
create policy "receipts: admin update" on public.payment_receipts
  for update using (public.is_admin());

create index if not exists receipts_user_idx on public.payment_receipts(user_id);

-- ---------------------------------------------------------------------
-- refunds: a returned item logged by a Cashier/Admin/Storekeeper. Kept
-- completely separate from stock_history and does NOT touch products.qty
-- until an Admin reviews it. Accepting it (in the app) adds the qty back
-- to the product and writes a matching 'refund' row to stock_history;
-- rejecting it just closes the request out with nothing added back.
-- ---------------------------------------------------------------------
create table if not exists public.refunds (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  product_name text not null,
  qty integer not null check (qty > 0),
  reason text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  staff text not null default 'Admin',
  requested_at timestamptz not null default now(),
  reviewed_by text,
  reviewed_at timestamptz
);

alter table public.refunds enable row level security;

create policy "refunds: owner all" on public.refunds
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "refunds: staff all" on public.refunds
  for all using (public.is_staff_of(user_id)) with check (public.is_staff_of(user_id));

create index if not exists refunds_user_idx on public.refunds(user_id);
create index if not exists refunds_status_idx on public.refunds(status);

-- ---------------------------------------------------------------------
-- Optional: seed a starter product once you have your first user.
-- Replace YOUR-USER-ID with the uuid from Authentication → Users.
-- ---------------------------------------------------------------------
-- insert into public.products (user_id, name, category, sku, qty, min_stock, purchase_price, selling_price, supplier)
-- values ('YOUR-USER-ID', 'Paracetamol 500mg', 'Medicine', 'TB-000101', 142, 40, 500, 800, 'ABC Pharma Supplies');

-- =====================================================================
-- Multi-user business: staff members sign in with their own account
-- (see is_staff_of() above and src/staffAuth.js), scoped to read/write
-- their employer's data via user_id, without a businesses/business_id
-- table — the existing user_id columns plus staff.auth_user_id are
-- enough for this app's shape (one owner + a staff roster per business).
-- =====================================================================
